name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - release-*
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - name: Enable pnpm
        run: corepack enable pnpm
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: 'https://npm.pkg.github.com'
          scope: '@seqsense'
          cache: pnpm

      - name: Run go vet
        run: GOOS=js GOARCH=wasm go vet ./...
      - name: Run go test
        run: go test ./... -v -race -coverprofile=cover.out -covermode atomic -coverpkg ./...
      - name: Build WASM
        run: make pcdeditor.wasm

      - uses: codecov/codecov-action@v5
        with:
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Install
        run: pnpm install
      - name: Type check
        run: pnpm typecheck
      - name: Set PACKAGE_VERSION
        run: |
          if [ -z "${PACKAGE_VERSION}" ]; then
            PACKAGE_VERSION=v0.0.0
          fi
          echo "${PACKAGE_VERSION}" | sed 's/^v//;s/^/PACKAGE_VERSION=/' >> ${GITHUB_ENV}
        env:
          PACKAGE_VERSION: ${{ github.event.release.tag_name }}
      - name: Pack
        run: |
          pnpm version ${PACKAGE_VERSION} --no-git-tag-version --allow-same-version
          make pack
      - name: Publish
        if: github.event_name == 'release'
        run: pnpm publish seqsense-pcdeditor-${PACKAGE_VERSION}.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
