name: eslint 
on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.13'
          cache: npm
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'pcdeditor.js pcdeditor.d.ts ReactPCDEditor/index.tsx'
