name: license collect
on:
  release:
    types: [created]

env:
  GOPRIVATE: github.com/seqsense/*

jobs:
  go-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Collect licenses
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/licenses
          for mod in $(find . -name go.mod); do
            echo 'replace github.com/google/go-licenses v0.0.0-20201026145851-73411c8fa237 => github.com/at-wat/go-licenses v0.0.0-20201126113030-93f9da6ba9f8' >> ${mod}

            (
              cd $(dirname ${mod})
              go install github.com/google/go-licenses
              export PATH=$PATH:$(go env GOPATH)/bin
              go-licenses save ./... \
                --ignore github.com/golang/freetype \
                --ignore github.com/seqsense/pcdeditor \
                --save_path ./.licenses --force
              chmod -R a+w ./.licenses
              cp -r .licenses/* ${GITHUB_WORKSPACE}/licenses/
            )
          done
          tar czf licenses.tar.gz ./licenses
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./licenses.tar.gz
          asset_name: licenses.tar.gz
          asset_content_type: application/gzip
