name: license check
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  GOPRIVATE: github.com/seqsense/*

jobs:
  go-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Install go-licenses
        run: go install github.com/google/go-licenses@latest
      - name: Check licenses
        run: |
          for mod in $(find . -name go.mod); do
            (
              cd $(dirname ${mod})
              go-licenses check ./... \
                  --ignore github.com/golang/freetype \
                  --ignore github.com/seqsense 2>&1 \
                | tee /dev/stderr | wc -l \
                | grep '^0$' > /dev/null
            )
          done
